spring:
  profiles:
    active: local

env:
  servers:
    - dev.example.com
    - prod.example.com

server:
  port: 8080
---
spring:
  profiles: local

  datasource:
    platform: h2
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop

---
#dev - local docker(mysql)
spring:
  profiles: dev

  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/slackapi?useSSL=false
    username: slackapi
    password: slackapi
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---
#prod - mysql server
spring:
  profiles: prod

  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/slackapi?useSSL=false&serverTimezone=Asia/Seoul
    username: slackapi
    password: slackapi
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
